### ISSUE TITLE
7C全新安装会出现503 Service Unavailable

### ISSUE THREAD

**Issue by rootphantomer** [skywalker512/FlarumChina#16]
git clone https://github.com/skywalker512/FlarumChina 
然后全新安装，点击安装后出现报错但无具体报错字样。最后访问首页显示 503 Service Unavailable

![default](https://user-images.githubusercontent.com/6481352/37019724-57344b38-2154-11e8-8f0d-9cc09ed57602.png)

**Comment by skywalker512** [comment]
请问是否能访问后台？

**Comment by rootphantomer** [comment]
@skywalker512 访问不了

**Comment by rootphantomer** [comment]
@skywalker512 又尝试了一下，可以访问后台，但是每次输入数据库密码后，还是重新跳转到需要输入数据库密码页面。

**Comment by skywalker512** [comment]
请删除数据库，安装一次
