### ISSUE TITLE
fontawesome资源文件位置

### ISSUE THREAD

**Issue by se4** [skywalker512/FlarumChina#6]
其他资源都是通过/assets目录进行读取，而fontawesome字库文件总是访问以下目录进行读取导致页面图标全部加载失败。

/lib/font-awesome/fonts/fontawesome-webfont.woff2?v=4.4.0

====================================
其他源正常读取路径是
/assets/fonts/fontawesome-webfont.woff2?v=4.4.0

=====================================
请问这个是个例？
rochexp/cklayflarum:6d88b0d(也是从您那fork来的)和官方的版本LAMP部署或者docker部署就没问题

**Comment by skywalker512** [comment]
请使用最新的https://github.com/skywalker512/FlarumChina/releases/tag/v0.1.0-beta.6.fix.2  release

**Comment by se4** [comment]
好的，解决了
